### PR TITLE
fix: Dumb operation fixes

### PR DESCRIPTION
**Pull request by FriiZe**
Hi master,
I was interested by this ugly project but I have some change to submit.
Are you serious ? You are not able to give attention to your code.
Please, be aware about your code. 
Or you are not able to make difference between an addition and a subtraction ? 
Regards,

### CODE REVIEW

**Comment by potb** [comment]
Hello @FriiZe, thank you for your **kind** comment.  
Looks like I don't do well with committing stuff at night...

**Comment by FriiZe** [comment]
@potb Please, next time try to be aware about of your code and test it.

**Comment by FriiZe** [comment]
@potb Please, next time try to be aware about your code and test it.
You should setup mocha or jest environment.
You can take a look too on CircleCi.

**Comment by potb** [comment]
Don't worry, that won't happen again.
Speaking of CI, I'm using GitHub Actions which is fine for the use I have.
Also, can you please rephrase your commit removing the capital D, as I didn't setup a commit message linting tool.
Thank you.

**Comment by FriiZe** [comment]
Woops sorry man ! I usually contribute to projects with pre-commit hooks and commit formatter like husky or commitizen :/ 
I will update my contribution.

**Comment by FriiZe** [comment]
@potb done

**Pull request merged**
